Resources:
  PlugMainTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: plug-prod
      AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsi1pk
            AttributeType: S
          - AttributeName: gsi1sk
            AttributeType: S
          - AttributeName: gsi2pk
            AttributeType: S
          - AttributeName: gsi2sk
            AttributeType: S
          - AttributeName: gsi3pk
            AttributeType: S
          - AttributeName: gsi3sk
            AttributeType: S
          - AttributeName: gsi4pk
            AttributeType: S
          - AttributeName: gsi4sk
            AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
     
      GlobalSecondaryIndexes:
          - IndexName: 'username-index'
            KeySchema:
                - AttributeName: gsi1pk
                  KeyType: HASH
                - AttributeName: gsi1sk
                  KeyType: RANGE
            Projection:
                ProjectionType: ALL
            

          - IndexName: 'name-index'
            KeySchema:
                - AttributeName: gsi2pk
                  KeyType: HASH
                - AttributeName: gsi2sk
                  KeyType: RANGE
            Projection:
                ProjectionType: ALL
           

          - IndexName: 'mobile-index'
            KeySchema:
                - AttributeName: gsi3pk
                  KeyType: HASH
                - AttributeName: gsi3sk
                  KeyType: RANGE
            Projection:
                ProjectionType: ALL
           
          - IndexName: 'event-tags'
            KeySchema:
                - AttributeName: gsi4pk
                  KeyType: HASH
                - AttributeName: gsi4sk
                  KeyType: RANGE
            Projection:
                ProjectionType: ALL

          - IndexName: 'event-trades'
            KeySchema:
                - AttributeName: gsi4pk
                  KeyType: HASH
                - AttributeName: gsi4sk
                  KeyType: RANGE
            Projection:
                ProjectionType: ALL